version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_customers
      - name: raw_events
      - name: raw_orders
      - name: raw_products
      - name: raw_support_tickets
